import requests

welcome = '''

   _____ _               _____        __      
  / ____| |             |_   _|      / _|     
 | |    | | __ _ ___ ___  | |  _ __ | |_ ___  
 | |    | |/ _` / __/ __| | | | '_ \|  _/ _ \ 
 | |____| | (_| \__ \__ \_| |_| | | | || (_) |
  \_____|_|\__,_|___/___/_____|_| |_|_| \___/ 
                                              
                                              
|---------------------------------------------|

'''

print(welcome) #Generated by https://patorjk.com/software/taag/#p=display&f=Big&t=ClassInfo

classCode = input('Class Code: ').upper()


def HookIntoClass(code):
    data={"class_code":code, "name":"ClassInjectionHook"}
    Hook = requests.post("https://services.classkick.com/v1/users/login/anonymous-student", json={"class_code":code, "name":"ClassInjectionHook"})
    return Hook.text



def getToken(code):
    token = HookIntoClass(code).split("token\":\"")[1].split("\"}")[0]
    print("Hook Token:  "+token)
    return token


def getRosterID(code):
    rosterid = HookIntoClass(code).split("roster_id\":\"")[1].split("\"")[0]
    print("Roster ID:  "+rosterid)
    return rosterid

def getAssignmentID(code):
    assignmentid = HookIntoClass(code).split("assignment_id\":\"")[1].split("\"")[0]
    print("Assignment Id:  "+assignmentid)
    return assignmentid


def getClassCodeTitle(code):

    headers = {
    "authorization": "Bearer "+getToken(code)
    }

    CodeTitle = requests.post("https://services.classkick.com/v1/assignment-works", json= {"assignment_id":getAssignmentID(code),"roster_id":getRosterID(code)}, headers=headers)
    print("Assignment Works:"+ CodeTitle.text)

    ownerID = CodeTitle.text.split("owner_id\":\"")[1].split("\"")[0]

    ownerName = requests.get("https://services.classkick.com/v1/users/"+ownerID+"/member-rosters", headers=headers).text
    print("-----------------")
    ownerNameFormatted = ownerName.split("first_name\":\"")[1].split("\"")[0]+ " "+ownerName.split("last_name\":\"")[1].split("\"")[0]
    
    #{"roster_owners":[{"first_name":"supriya","last_name":"Sundram","display_name":"Ms. Sundram","id":"AXKXznG7Q6u6_69b-CB1gQ","contract_ids":[],"auth_types":[]}],"rosters":[{"id":"AXKXznK1S-uYBZJ-8gVpqA","owner_id":"AXKXznG7Q6u6_69b-CB1gQ","name":"Sample Roster","color":"#EA4494","allow_peer_help":false,"allow_new_members":true,"allow_multi_login":true,"properties":{}}]}
    idAssignmentWorks = CodeTitle.text.split("id\":\"")[1].split("\"")[0]

    assignment = requests.get("https://services.classkick.com/v1/assignment-works/"+idAssignmentWorks+"/assignment", headers=headers).text
    

    print("\n\n\n\n\n\n\n\n\n")
    print(welcome)
    print("Class Code: "+ code)
    print("Owner Name: "+ownerNameFormatted.title())
    print("Name Of Assignment:  "+assignment.split("name\":\"")[1].split("\"")[0]) 

getClassCodeTitle(classCode)
input('Press Enter to quit the program')